### ISSUE TITLE
Application to Deformation in General

### ISSUE THREAD

**Issue by ynffsy** [alexeybokhovkin/CAD-Deform#1]
I understand that the pipeline of this project is to deform objects in a scanned scene to CAD models in databases. But if I have a source mesh and a target mesh (or a target point cloud), would it be possible for this project to work in this case? If so, what part of it should I use? Thank you very much.

**Comment by liaoksn** [comment]
> I understand that the pipeline of this project is to deform objects in a scanned scene to CAD models in databases. But if I have a source mesh and a target mesh (or a target point cloud), would it be possible for this project to work in this case? If so, what part of it should I use? Thank you very much.

the same question

**Comment by alexeybokhovkin** [comment]
Yes, of course! Thanks for the great question. All you need to do is extract points from the target mesh (or just have a target point cloud) and then perform the coarse alignment before applying CAD-Deform. The alignment can be done using some point- or feature-matching algorithms and optionally ICP.
